Repository GraphFilter/GraphFilter, pull requests merged in 2023-06, with the labels that each got.

#322 Implement a QMenu to export in another format
  requirements.txt
  resources/icons/export.png
  source/controller/project_controller.py
  source/domain/exports.py
  source/domain/utils_file.py
  source/store/export_graph_to.py
  source/view/project/docks/tree_file_dock.py
  source/view/project/project_tool_bar.py
  source/view/project/project_window.py
Labels: enhancement

#335 Bug fixes on method page button crashes
  source/controller/wizard_controller.py
Labels: bug, important

#347 Fix bug on universal vertex with none graph
  source/controller/project_controller.py
Labels: bug

#343 Optimization of controller methods
  source/controller/controller.py
  source/controller/filter_controller.py
  source/controller/project_controller.py
  source/controller/wizard_controller.py
  source/domain/utils.py
  source/store/export_graph_to.py
  source/view/components/message_box.py
  source/view/wizard/pages/files_page.py
Labels: code optimization

#346 Limit name of file in toolbar
  source/view/project/project_tool_bar.py
Labels: bug

#352 Bug fixes in loading gif window
  source/view/components/message_box.py
Labels: bug

#349 Fix bug on open gml file from tree
  source/domain/utils_file.py
Labels: bug

#355 Two tabs to spectral invariants
  source/controller/wizard_controller.py
  source/store/operations_and_invariants/num_invariants.py
Labels: enhancement

#359 Program freezes when export to g6 or txt
  source/domain/utils_file.py
  source/store/export_graph_to.py
Labels: bug

#345 Delete graph function with. gml
  source/controller/project_controller.py
  source/domain/utils_file.py
Labels: bug

#364 Change logo path on pdf model
  source/domain/pdf_model.py
Labels: bug

#366 Progress bar cancels the process
  source/controller/controller.py
  source/controller/filter_controller.py
  source/domain/exports.py
  source/domain/filter_list.py
  source/view/loading/loading_window.py
Labels: bug

#369 Disable combo on gml graphs from tree
  source/controller/project_controller.py
Labels: bug

#350 Implement loading window to long operations
  resources/gifs/loading.gif
  source/controller/project_controller.py
  source/store/operations_and_invariants/invariants.py
  source/view/components/message_box.py
  source/view/loading/loading_gif.py
  source/view/project/project_tool_bar.py
Labels: enhancement

#372 Template new issue for user
  source/controller/project_controller.py
Labels: enhancement

#376 Fix double click folder bug
  source/controller/project_controller.py
  source/view/loading/loading_gif.py
Labels: bug

#371 Fix bug on start blank project
  source/controller/controller.py
  source/controller/project_controller.py
Labels: bug
