Repository GraphFilter/GraphFilter, pull requests merged in 2023-10, with the labels that each got.

#403 Fix the writing of a new graph in a g6 file
  source/domain/utils_file.py
  source/view/project/docks/visualize_graph_dock.py
Labels: bug

#405 Typo on Wizard Method
  resources/images/wizard_method.png
  source/view/wizard/pages/method_page.py
Labels: bug

#404 Bug on `Inverse Line Graph`
  source/store/operations_graph.py
Labels: bug

#406 Graph plotting problem
  source/store/new_graph_store.py
  source/view/project/docks/visualize_graph_dock.py
Labels: bug

#412 Graph count on combo box start at 1
  source/domain/exports.py
  source/view/project/project_tool_bar.py
Labels: update

#413 Add default name and folder to export excel file
  source/controller/controller.py
  source/domain/utils_file.py
  source/store/export_graph_to.py
  source/store/project_information_store.py
Labels: update

#417 Set title bar when showing project window
  source/controller/controller.py
Labels: bug

#420 Gif not loading on README
  README.md
Labels: bug, documentation

#418 Fix smallest eigenvalue for disconnected graphs
  source/controller/wizard_controller.py
  source/store/operations_and_invariants/bool_invariants.py
  source/store/operations_and_invariants/invariants.py
  source/store/operations_and_invariants/num_invariants.py
  source/store/operations_and_invariants/other_invariants.py
  test/domain/unit_tests.py
Labels: bug, enhancement

#415 Implementation new spectral invariants: Kirchhoff and Randic
  test/domain/unit_tests.py
Labels: enhancement

#411 Update on spectral invariants and name optimization
  source/store/operations_and_invariants/bool_invariants.py
  test/domain/unit_tests.py
Labels: enhancement

#419 Update wizard helper texts
  source/store/help_button_text.py
  source/view/wizard/pages/review_page.py
Labels: update

#423 Update welcome window version
  resources/images/welcome_window.png
  source/view/project/about_window.py
  source/view/welcome/welcome_content.py
Labels: enhancement, important

#425 Set documents as default export folder
  source/controller/controller.py
  source/domain/utils_file.py
Labels: update
