Repository GraphFilter/GraphFilter, pull requests merged in 2023-07, with the labels that each got.

#386 Update graph files to manual test
  Graph1.gml
  Graph2.gml
  SomeGraphs.g6
  test/domain/resources/graphs/Example PDF Report.pdf
  test/domain/resources/graphs/GraphGML.gml
  test/domain/resources/graphs/json_file_graphs.json
Labels: enhancement

#387 Mac problems pre release
  source/controller/project_controller.py
  source/domain/utils.py
  source/domain/utils_file.py
  source/view/project/docks/visualize_graph_dock.py
  source/view/project/project_tool_bar.py
  source/view/project/project_window.py
Labels: bug, code optimization

#380 Bugs on plotting some graphs
  source/controller/controller.py
  source/controller/project_controller.py
  source/domain/utils.py
  source/domain/utils_file.py
  source/store/new_graph_store.py
  source/view/project/project_tool_bar.py
Labels: bug

#392 Implement chromatic index
  source/store/operations_and_invariants/num_invariants.py
  source/store/operations_and_invariants/other_invariants.py
  test/domain/unit_tests.py
Labels: enhancement

#393 Problem to multiprocessing in executabe
  app.py
  source/controller/controller.py
  source/store/operations_and_invariants/num_invariants.py
  source/view/project/about_window.py
  source/view/welcome/welcome_content.py
Labels: bug
