Repository GraphFilter/GraphFilter, pull requests merged in 2023-05, with the labels that each got.

#293 Delete file function
  source/controller/controller.py
  source/controller/project_controller.py
  source/store/new_graph_store.py
  source/store/project_information_store.py
  source/view/project/docks/tree_file_dock.py
Labels: enhancement

#305 Updated file export and menu
  source/controller/controller.py
  source/view/project/docks/tree_file_dock.py
  source/view/project/project_window.py
Labels: enhancement, Code Optimization

#303 Update restore view for the tree file
  source/controller/project_controller.py
  source/view/project/project_window.py
Labels: enhancement

#311 Project window restore with cancel new project
  source/controller/controller.py
  source/controller/project_controller.py
Labels: bug

#332 Bugfixes in exports
  source/controller/controller.py
Labels: bug

#323 Implement Threshold in ```New Graph```
  source/controller/project_controller.py
  source/domain/utils.py
  source/store/new_graph_store.py
Labels: enhancement
